    modLoader="javafml"
    loaderVersion="[33,)"
    showAsResourcePack=false

    [[mods]]
      modId="evolutionterraingenerator"
      version="${version}"
      displayName="Evolution Terrain Generator"
      credits="Mojang for base terrain generators
  Kurt \"KdotJPG\" Spencer for Open Simplex Noise generator"
      authors="12ofspades"
      description='''
  A new world take on the terrain generation featuring the best of all of the vanilla Minecraft terarain generators in history and more'''

      [[dependencies.evolutionterraingenerator]]
        modId="forge"
        mandatory=true
        versionRange="[33,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.evolutionterraingenerator]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.2]"
        ordering="NONE"
        side="BOTH"