    modLoader="javafml"
    loaderVersion="[31,)"
    showAsResourcePack=false

    [[mods]]
      modId="evolutionterraingenerator"
      version="${version}"
      displayName="Evolution Terrain Generator"
      credits="Mojang for base terrain generators
  Kurt \"KdotJPG\" Spencer for Open Simplex Noise generator"
      authors="12ofspades"
      description='''
  A new take on the terrain generation of Minecraft featuring the best of all of the vanilla Minecraft terarain generators in history and more!
      '''

      [[dependencies.evolutionterraingenerator]]
        modId="forge"
        mandatory=true
        versionRange="[31,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.evolutionterraingenerator]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"